MODEL:
  META_ARCHITECTURE: "PanopticFCN"
  # WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
#   WEIGHTS: "../../input/weights/R-50.pkl"
  WEIGHTS: "../../data/pretrained/R-50.pkl"
  MASK_ON: True
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [1.0, 1.0, 1.0]
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  LOSS_WEIGHT:
    SEGMENT: 4.0
  POSITION_HEAD:
    THING:
      NUM_CLASSES: 8
      THRES: 0.01
      TOP_NUM: 200
    STUFF:
      THRES: 0.1
      NUM_CLASSES: 19
      WITH_THING: False  # Check that this is not a problem
      ALL_CLASSES: True
  SEM_SEG_HEAD:
    NUM_CLASSES: 19
  KERNEL_HEAD:
    INSTANCE_SCALES: ((1, 128), (64, 256), (128, 512), (256, 1024), (512, 2048),)
  TENSOR_DIM: 150  # Adapted because max inst. per img > 100
  INFERENCE:
    INST_THRES: 0.5
    SIMILAR_THRES: 0.97
    COMBINE:
      STUFF_AREA_LIMIT: 2048
DATASETS:
  NAME: "Cityscapes"
  TRAIN: ("cityscapes_fine_panoptic_train_separated",)
  TEST: ("cityscapes_fine_panoptic_val_separated",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 2
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 1e-4
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  POLY_LR_POWER: 0.9
  WARMUP_ITERS: 1000
  WARMUP_FACTOR: 0.001
  WARMUP_METHOD: "linear"
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_VALUE: 15.0
  IMS_PER_BATCH: 8
#   MAX_ITER: 65000
  MAX_ITER: 45
#   CHECKPOINT_PERIOD: 20000
  CHECKPOINT_PERIOD: 20
INPUT:
  MIN_SIZE_TRAIN: (512, 768, 1024, 1152, 1216, 1344, 1408, 1536, 1664, 1728, 1856, 1920, 2048)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 4096
  MAX_SIZE_TEST: 2048
  CROP:
    MINIMUM_INST_AREA: 1
    ENABLED: True
    TYPE: "absolute"
    SIZE: (512, 1024)
  MASK_FORMAT: "bitmask"
VERSION: 2

